### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [littledata/gtm-variable#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) We are seeing "TypeError: cannot access property of undefined." error while trying to "Run Code". Please resolve the issue.
![Screenshot 2021-04-15 11 05 26 AM](https://user-images.githubusercontent.com/53495700/114917282-a3b65900-9dda-11eb-9361-a472c2f82bbb.png)

**Comment by igorkol** [comment]
Hi @praveena-pappu !

Thank you for such a quick feedback and review. 

This is a template that depends on the usage of Littledata Shopify app ( https://apps.shopify.com/littledata ), meaning that the app needs to be present on the Shopify site in order for the JS variable to be available for GTM to pick it up. I would assume you haven't tested it on a Shopify website with our app, which is why you were getting that error.

However, I have set the check for presence of Littledata JS variable and updated the file. The error is thus resolved and won't appear for non-Shopify or non-Littledata users.

Please retest it on our dev/demo Shopify store as well if you like: https://littledata.myshopify.com/

Thanks
Igor

**Comment by edwardupton** [comment]
@praveena-pappu please review the changes when you have time

**Comment by edwardupton** [comment]
@praveena-pappu did you get a chance to review?

**Comment by igorkol** [comment]
@praveena-pappu any updates? Are we maybe missing some detail in the instructions on how to resubmit the template for another review? Is there another way to reach out to you or your team?

**Comment by praveena-pappu** [comment]
Hello,

The pull request is approved and merged.

**Comment by igorkol** [comment]
Thank you @praveena-pappu
